[dock.icons.common]
to_add = [
    "Finder",
    "Microsoft Edge",
    "Obsidian",
    "UPDF"
]

[dock.icons.personal_computer]
to_add = []

[dock.icons.work_computer]
to_add = []

[dock.icons.dev_computer]
to_add = []

[dock.icons.docker_computer]
to_add = []
